import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Todo-List Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-blue-800 ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <div className="relative w-full h-screen">
  <Image 
    src="/u105ro5rg8o31.jpg"
    alt="image"
    layout="fill"
    objectFit="cover"
    quality={100}
    className="z-0" // This ensures the image is behind the content
  />
  <div className="relative z-10">
    {children}
  </div>
</div>


      </body>
    </html>
  );
}
